#!/usr/bin/env python
#-*- coding: utf-8 -*-

import os,sys,re
import subprocess
class CheckEenv:
    def __init__(self):
        pass
    def check_net(ip):
        try:
            p = subprocess.Popen(["ping -c 1 -w 1 "+ ip],stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=True)
            out=p.stdout.read().decode('utf-8')
            regex=re.compile('100% packet loss')
            if len(regex.findall(out)) == 0:
                print (ip + ': host up')
                return True
            else:
                print (ip + ': host down')
            return False
        except:
            print("check error")

if __name__ == '__main__':
    check=CheckEenv()
    if check.check_net('8.8.8.8'):
        print("The network is working")
    else:
        print("Network failure")
